package komis.db.dao;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;






import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;

import komis.Client;
import komis.db.DaoBase;
import komis.db.EntityBase;
import komis.db.MysqlUnitOfWork;

public class MysqlClientDao extends DaoBase<Client> implements ClientDao {
	
	 private Statement stmt;
     private PreparedStatement insert;
     private PreparedStatement delete;
     private PreparedStatement update;
     private PreparedStatement select;
     private PreparedStatement selectId;
    
	
	public MysqlClientDao(MysqlUnitOfWork uow){
			
		super(uow);
			try
			{
			    Connection connection = uow.getConnection();
				ResultSet rs = connection.getMetaData().getTables(null,null,null,null);
             
				
				boolean exist = false;
				
				stmt =(Statement) connection.createStatement();
				
				while (rs.next())
				{
						if(rs.getString("TABLE_NAME").equalsIgnoreCase("Client"))
						{
							exist=true;
							break;
				
						}
				}
				if(!exist)
				{
					stmt.executeUpdate("CREATE TABLE Client("
					                 + "id int GENERATED BY DEFAULT AS IDENTITY ,"
					                 + "name VARCHAR(50),"
					                 + "surname VARCHAR(50),"
					                 + "pesel VARCHAR(11),"
                                     + "city VARCHAR(50),"
					                 + "street VARCHAR(40),"
                                     + "number integer"
                                     + ")"
                                     + "");
							
					
				}
						insert = connection.prepareStatement(""
						+ "insert into Client(id,name,surname,pesel,city,street,number) values (?,?,?,?,?,?,?)");
						
						update = connection.prepareStatement(""
								+" update Client set"
								+"(name,surname,pesel,city,street,number)=(?,?,?,?,?,?)"
								+ "where id =?");
						
						delete = connection.prepareStatement(""
								+ "delete from Client where id =?");
						selectId = connection.prepareStatement(" select * from Client where id= ?");
						
						select = connection.prepareStatement("select * from Client");
			}
			
			
					catch (Exception e)
					{
						e.printStackTrace();
					}
		}

	public void persistAdd(EntityBase entity) {

		Client ent = (Client) entity;
		
		try 
		{	insert.setInt(1, ent.getId());
			insert.setString(2, ent.getName());
			insert.setString(3, ent.getSurname());
			insert.setString(4, ent.getPesel());
			insert.setString(5, ent.getCity());
			insert.setString(6, ent.getStreet());
			insert.setString(7, ent.getNumber());
			insert.executeUpdate();
		} 
		
		catch (SQLException e) 
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	
	public void persistDelete(EntityBase entity) {
		
		Client ent = (Client) entity;
		try 
		{
			delete.setInt(1,  ent.getId());
			delete.executeUpdate();
		} 
		
		catch (SQLException e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	}

	
	public void persistUpdate(EntityBase entity) {
	Client ent = (Client) entity;
		try {
			update.setString(1, ent.getName());
			update.setString(2, ent.getSurname());
			update.setString(3, ent.getNumber());
			update.setString(4, ent.getCity());
			update.setString(5, ent.getStreet());
			update.setString(6, ent.getPesel());
			update.setInt(7, ent.getId());
			update.executeUpdate();
			
			} 
		catch (SQLException e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
	}

	@Override
	
	public List<Client> getAll() {
		List<Client> clients = new ArrayList<Client>();

		try 
		{
			ResultSet rs = select.executeQuery();
			while(rs.next()){
        	
				Client c = new Client();
        		c.setName(rs.getString("name"));
        		c.setSurname(rs.getString("surname"));
        		c.setPesel(rs.getString("pesel"));
        		c.setCity(rs.getString("city"));
        		c.setStreet(rs.getString("street"));
        		c.setNumber(rs.getString("number"));
        		c.setId(rs.getInt("id"));
        		clients.add(c);
        		}
		        
		}
		
		catch (SQLException e) 
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return clients;
	}

	@Override
	public Client get(int id) {

		try {
			selectId.setInt(1, id);
		
		ResultSet rs = selectId.executeQuery();
		while(rs.next()){
			
			Client c = new Client();
    		c.setName(rs.getString("name"));
    		c.setSurname(rs.getString("surname"));
    		c.setPesel(rs.getString("pesel"));
    		c.setCity(rs.getString("city"));
    		c.setStreet(rs.getString("street"));
    		c.setNumber(rs.getString("number"));
    		c.setId(rs.getInt("id"));
    		return c;
    		}	
		
		} 
		catch (SQLException e) 
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
	return null;
		
	}

	@Override
	public void setTransaction(Client c) {
		// TODO Auto-generated method stub
		
	}

		
	
	

}
